#!/bin/sh

run_confd()
{
  confd -backend "rancher" -prefix "/2015-07-25" -log-level "debug"
}

# Copy the running script
mv /tmp/start_consul.sh /opt/rancher/bin
sed -i 's|/service/consul|/service/${sn:=consul}|g' /etc/confd/conf.d/*
run_confd
